# SPDX-License-Identifier: AGPL-3.0-only

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-nginx-manager
PKG_VERSION:=1.8.5
PKG_RELEASE:=1

PKG_LICENSE:=AGPL-3.0-only
PKG_MAINTAINER:=yunshu

LUCI_TITLE:=Nginx Manager for LuCI
LUCI_DEPENDS:=+luci-base +nginx-ssl +rpcd +rpcd-mod-file +openssl-util +acme +acme-acmesh-dnsapi +diffutils +flock
LUCI_PKGARCH:=all

include $(INCLUDE_DIR)/package.mk

define Package/luci-app-nginx-manager
  SECTION:=luci
  CATEGORY:=LuCI
  SUBMENU:=3. Applications
  TITLE:=$(LUCI_TITLE)
  DEPENDS:=$(LUCI_DEPENDS)
  PKGARCH:=$(LUCI_PKGARCH)
endef

define Package/luci-app-nginx-manager/description
  Complete Nginx management plugin for OpenWrt LuCI.
  Provides site management, reverse proxy, SSL certificates,
  logs, configuration testing, backup and rollback.
endef

define Build/Compile
	mkdir -p $(PKG_BUILD_DIR)/lmo; \
	for po_dir in $(CURDIR)/po/*/; do \
		[ -d "$$$$po_dir" ] || continue; \
		lang=$$$$(basename "$$$$po_dir"); \
		[ "$$$$lang" = "templates" ] && continue; \
		[ -f "$$$$po_dir/nginx-manager.po" ] || continue; \
		lmo_lang="$$$$lang"; \
		[ "$$$$lmo_lang" = "zh_Hans" ] && lmo_lang="zh-cn"; \
		if [ -x "$(STAGING_DIR_HOSTPKG)/bin/po2lmo" ]; then \
			"$(STAGING_DIR_HOSTPKG)/bin/po2lmo" "$$$$po_dir/nginx-manager.po" "$(PKG_BUILD_DIR)/lmo/nginx-manager.$$$$lmo_lang.lmo"; \
		fi; \
	done
endef

define Package/luci-app-nginx-manager/install
	$(INSTALL_DIR) $(1)/etc/config
	$(INSTALL_CONF) ./root/etc/config/nginx_manager $(1)/etc/config/nginx_manager

	$(INSTALL_DIR) $(1)/etc/uci-defaults
	$(INSTALL_BIN) ./root/etc/uci-defaults/90-luci-app-nginx-manager $(1)/etc/uci-defaults/90-luci-app-nginx-manager

	$(INSTALL_DIR) $(1)/usr/sbin
	$(INSTALL_BIN) ./root/usr/sbin/nginx-manager-gen $(1)/usr/sbin/nginx-manager-gen
	$(SED) 's/@PKG_VERSION@/$(PKG_VERSION)/' $(1)/usr/sbin/nginx-manager-gen

	$(INSTALL_DIR) $(1)/etc/init.d
	$(INSTALL_BIN) ./root/etc/init.d/nginx_manager $(1)/etc/init.d/nginx_manager

	$(INSTALL_DIR) $(1)/usr/libexec/rpcd
	$(INSTALL_BIN) ./root/usr/libexec/rpcd/nginx_manager $(1)/usr/libexec/rpcd/nginx_manager

	$(INSTALL_DIR) $(1)/usr/share/luci/menu.d
	$(INSTALL_DATA) ./root/usr/share/luci/menu.d/luci-app-nginx-manager.json $(1)/usr/share/luci/menu.d/luci-app-nginx-manager.json

	$(INSTALL_DIR) $(1)/usr/share/rpcd/acl.d
	$(INSTALL_DATA) ./root/usr/share/rpcd/acl.d/luci-app-nginx-manager.json $(1)/usr/share/rpcd/acl.d/luci-app-nginx-manager.json

	$(INSTALL_DIR) $(1)/www/luci-static/resources/nginx-manager
	$(INSTALL_DATA) ./www/luci-static/resources/nginx-manager/nginx-manager.css $(1)/www/luci-static/resources/nginx-manager/nginx-manager.css
	$(INSTALL_DATA) ./www/luci-static/resources/nginx-manager/file-icons.svg $(1)/www/luci-static/resources/nginx-manager/file-icons.svg
	$(INSTALL_DATA) ./www/luci-static/resources/nginx-manager/utils.js $(1)/www/luci-static/resources/nginx-manager/utils.js
	$(SED) 's/@PKG_VERSION@/$(PKG_VERSION)/g' $(1)/www/luci-static/resources/nginx-manager/utils.js

	$(INSTALL_DIR) $(1)/www/luci-static/resources/view/nginx-manager
	$(INSTALL_DATA) ./www/luci-static/resources/view/nginx-manager/overview.js $(1)/www/luci-static/resources/view/nginx-manager/overview.js
	$(INSTALL_DATA) ./www/luci-static/resources/view/nginx-manager/sites.js $(1)/www/luci-static/resources/view/nginx-manager/sites.js
	$(INSTALL_DATA) ./www/luci-static/resources/view/nginx-manager/site-edit.js $(1)/www/luci-static/resources/view/nginx-manager/site-edit.js
	$(INSTALL_DATA) ./www/luci-static/resources/view/nginx-manager/certificates.js $(1)/www/luci-static/resources/view/nginx-manager/certificates.js
	$(INSTALL_DATA) ./www/luci-static/resources/view/nginx-manager/logs.js $(1)/www/luci-static/resources/view/nginx-manager/logs.js
	$(INSTALL_DATA) ./www/luci-static/resources/view/nginx-manager/core-config.js $(1)/www/luci-static/resources/view/nginx-manager/core-config.js
	$(INSTALL_DATA) ./www/luci-static/resources/view/nginx-manager/backups.js $(1)/www/luci-static/resources/view/nginx-manager/backups.js
	$(INSTALL_DATA) ./www/luci-static/resources/view/nginx-manager/files.js $(1)/www/luci-static/resources/view/nginx-manager/files.js

	if [ -n "$$$$(ls $(PKG_BUILD_DIR)/lmo/*.lmo 2>/dev/null)" ]; then \
		$(INSTALL_DIR) $(1)/usr/lib/lua/luci/i18n; \
		$(INSTALL_DATA) $(PKG_BUILD_DIR)/lmo/*.lmo $(1)/usr/lib/lua/luci/i18n/; \
	fi
endef

define Package/luci-app-nginx-manager/postinst
#!/bin/sh
[ -n "$${IPKG_INSTROOT}" ] || {
	mkdir -p /etc/nginx/conf.d/luci-manager/sites
	mkdir -p /etc/nginx/conf.d/luci-manager/disabled
	mkdir -p /etc/nginx/certs/luci-manager
	mkdir -p /etc/nginx-manager/backups

	cat > /etc/nginx/conf.d/luci-manager.conf <<'NGINX_MGR_CONF'
# Generated by luci-app-nginx-manager.
# Source: /etc/config/nginx_manager
# SPDX-License-Identifier: AGPL-3.0-only

include /etc/nginx/conf.d/luci-manager/*.conf;
include /etc/nginx/conf.d/luci-manager/sites/*.conf;
NGINX_MGR_CONF

	uci -q get nginx_manager.global >/dev/null 2>&1 || {
		uci set nginx_manager.global=global
		uci set nginx_manager.global.managed_dir='/etc/nginx/conf.d/luci-manager'
		uci set nginx_manager.global.cert_dir='/etc/nginx/certs/luci-manager'
		uci set nginx_manager.global.backup_dir='/etc/nginx-manager/backups'
		uci set nginx_manager.global.auto_backup='1'
		uci set nginx_manager.global.test_before_reload='1'
		uci set nginx_manager.global.advanced_mode='0'
		uci set nginx_manager.global.dangerous_core_edit='0'
		uci set nginx_manager.global.max_backups='5'
		uci set nginx_manager.global.client_max_body_size=''
		uci set nginx_manager.global.keepalive_timeout=''
		uci set nginx_manager.global.gzip='0'
		uci set nginx_manager.global.server_tokens=''
		uci set nginx_manager.global.sendfile='0'
		uci set nginx_manager.global.access_log=''
		uci set nginx_manager.global.error_log=''
		uci set nginx_manager.global.ssl_protocols=''
		uci set nginx_manager.global.ssl_ciphers=''
		uci commit nginx_manager
	}

	changed=0; \
	uci -q get nginx_manager.global.max_backups >/dev/null 2>&1 || { \
		uci set nginx_manager.global.max_backups='20'; \
		changed=1; \
	}; \
	[ "$${changed}" = "1" ] && uci commit nginx_manager; \

	uci -q get luci.languages.zh_cn >/dev/null || uci -q set luci.languages.zh_cn='简体中文'; \
	uci -q commit luci; \

	chmod 600 /etc/config/nginx_manager 2>/dev/null

	rm -f /etc/uci-defaults/90-luci-app-nginx-manager
	rm -f /tmp/luci-indexcache.*
	rm -rf /tmp/luci-modulecache/
	if [ -x /etc/init.d/nginx_manager ]; then
		/etc/init.d/nginx_manager enable 2>/dev/null
		/etc/init.d/nginx_manager start 2>/dev/null
	fi
	/etc/init.d/rpcd reload 2>/dev/null
}
exit 0
endef

define Package/luci-app-nginx-manager/postrm
#!/bin/sh
[ -n "$${IPKG_INSTROOT}" ] || {
	rm -f /tmp/luci-indexcache.*
	rm -rf /tmp/luci-modulecache/
}
exit 0
endef

$(eval $(call BuildPackage,luci-app-nginx-manager))
