name: Cleanup Workflow Runs

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    name: Cleanup old workflow runs
    runs-on: ubuntu-latest

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          retain_days: 30
          keep_minimum_runs: 10
